services:
  # Enhanced Medical Dictation App v3.0
  - type: web
    name: medical-dictation-app-v3
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: cd src && python -m gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: OPENAI_API_KEY
        sync: false
      - key: CLAUDE_API_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: medical-dictation-redis
          property: connectionString
    healthCheckPath: /api/health
    
  # Redis for background processing
  - type: redis
    name: medical-dictation-redis
    region: oregon
    plan: starter
    maxmemoryPolicy: allkeys-lru

