version: '3.8'

services:
  medical-dictation-app:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    ports:
      - "10000:10000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - PORT=10000
      # Add your OpenAI API key here or use .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      # Mount logs directory for persistence
      - ./logs:/app/logs
      # Mount uploads directory for file uploads
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - medical-dictation-app
  #   restart: unless-stopped

volumes:
  logs:
  uploads:

